version: "3"

services:
  postgresql:
    platform: linux/amd64
    image: postgres:13
    container_name: prisma_postgresql
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
