import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthSessionProvider from "@/components/provider/session-provider";
import ReactQueryProvider from "@/components/provider/query-provider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth-options";
import AlertProvider from "@/components/provider/alert-provider";
import ModalProvider from "@/components/provider/modal-provider";
import SocketProvider from "@/components/provider/socket-provider";
import UserConnectionProvider from "@/components/provider/user-connection-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface ILayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: ILayoutProps) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <AlertProvider>
          <AuthSessionProvider session={session}>
            <SocketProvider>
              <UserConnectionProvider>
                <ReactQueryProvider>
                  <ModalProvider>{children}</ModalProvider>
                </ReactQueryProvider>
              </UserConnectionProvider>
            </SocketProvider>
          </AuthSessionProvider>
        </AlertProvider>
      </body>
    </html>
  );
}
